### ISSUE TITLE
Pairing with Win10

### ISSUE THREAD

**Issue by soffer** [getsenic/nuimo-windows-demo#2]
Anything I need to know to be able to pair my PC?
Win 10, BT enabled, PC recognizes Nuimo yet pairing does not work.

**Comment by larsblumberg** [comment]
Hi @soffer – Does this manual help you to connect your Nuimo? http://www.windowscentral.com/how-and-why-use-bluetooth-on-windows-10

Does your PC actually support Bluetooth Low Energy?

**Comment by soffer** [comment]
Hey Lars, thanks.
The problem seems to be a connecting and disconnecting cycle that occurs every once in awhile.
I'll make some progress on my attempt at actually creating something useful and functioning (Premiere Pro control on Win) and then update.
Cheers

**Comment by larsblumberg** [comment]
Cool – please keep us updated about your project!
